# Generated by Django 2.1 on 2018-08-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='True', max_length=32)),
                ('student_name', models.TextField(null=True)),
            ],
        ),
    ]
